apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-definitionssss
  namespace: "naap-dev"
type: Opaque
stringData:
  definitions.json: |
    {
        "users": [
          {
            "name": "integration",
            "password": "integration#",
            "tags": "administrator"
          }
        ],
        "permissions": [
          {
            "configure": ".*",
            "read": ".*",
            "user": "integration",
            "vhost": "/",
            "write": ".*"
          }
        ],
        "policies": [
          {
            "apply-to": "all",
            "definition": {
              "ha-mode": "all",
              "ha-sync-mode": "automatic"
            },
            "name": "ha-all",
            "pattern": ".",
            "priority": 0,
            "vhost": "/"
          }
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ]
      }
