name: Deployment

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Please provide the release version'
        required: true
      rabbitmq:
        description: 'Please provide the image tag'
        required: true

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest' # Specify a stable version if needed, e.g., '1.27.0'

      - name: Configure Kubeconfig
        run: |
          kubectl version

      - name: Get Kubernetes Pods
        run: |
          kubectl get pods -A

      - name: Apply Kubernetes Manifests with Inputs
        run: |
          kubectl version
          kubectl config get-contexts
          echo "Manifest updated for release: ${{ github.event.inputs.release }}"

      - name: Verify Deployment
        run: |
          echo "Deployment completed successfully."
