name: Deployment

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Please provide the release version'
        required: true
      rabbitmq:
        description: 'Please provide the image tag'
        required: true

jobs:
  deploy:
    env:
      POD_KUBECONFIG: '${{ github.workspace }}/.kube/pod-kubeconfig'
    name: Deployment
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Set up Kubectl
         uses: azure/k8s-set-context@v1
         with:
           kubeconfig: ${{ secrets.KUBECONFIG }}

       - name: Verify Kubernetes Connection
         run: kubectl cluster-info

       - name: List Pods
         run: kubectl get pods
