name: Deployment

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Please provide the release version'
        required: true
      rabbitmq:
        description: 'Please provide the image tag'
        required: true

jobs:
  deploy:
    env:
      POD_KUBECONFIG: '${{ github.workspace }}/.kube/pod-kubeconfig'
    name: Deployment
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Configure kubectl
         run: |
           mkdir -p '${{ github.workspace }}/.kube' \
            && echo '${{ secrets.KUBECONFIG}}' | base64 -d > $POD_KUBECONFIG
           kubectl version
           kubectl config get-contexts
           kubectl get pod
