name: Deployment

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Please provide the release version'
        required: true
        default: ''
      rabbitmq:
        description: 'Please provide the image tag'
        required: true
        default: ''

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
      - name: Apply Kubernetes Manifests with Inputs
        run: |
          kubectl version
          kubectl config get-contexts
          echo "manifest updated ${{ inputs.release }}"

      - name: Verify Deployment
        run: |
          echo "Deployment completed"
