name: Deployment

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Please provide the release version'
        required: true
        default: ''
      rabbitmq:
        description: 'Please provide the image tag'
        required: true
        default: ''

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          kubectl config get-contexts

      - name: Get Kubernetes Pods
        uses: actions-hub/kubectl@master
        with:
          args: get pods -A
          
      - name: Apply Kubernetes Manifests with Inputs
        run: |
          kubectl version
          kubectl config get-contexts
          echo "manifest updated ${{ inputs.release }}"

      - name: Verify Deployment
        run: |
          echo "Deployment completed"
