name: Deployment

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Please provide the release version'
        required: true

jobs:
  deploy:
    env:
      POD_KUBECONFIG: '${{ github.workspace }}/.kube/pod-kubeconfig'
    name: Deployment
    runs-on: [self-hosted, kube-deploy] 

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: custom-workspace  # Set the custom workspace directory

      - name: Verify workspace
        run: ls -la custom-workspace  # List files to verify checkout location
