name: Deployment

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Please provide the release version'
        required: true
      rabbitmq:
        description: 'Please provide the image tag'
        required: true

jobs:
  deploy:
    env:
      POD_KUBECONFIG: '${{ github.workspace }}/.kube/pod-kubeconfig'
    name: Deployment
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: kubectl installation
         run: |
          curl -LO "https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

       - name: Configure kubectl
         run: |
           mkdir -p '${{ github.workspace }}/.kube'
           echo '${{ secrets.KubeConfig }}' | base64 --decode > $POD_KUBECONFIG
           export KUBECONFIG=$POD_KUBECONFIG
           echo "KUBECONFIG=$POD_KUBECONFIG" >> $GITHUB_ENV

       - name: Verify Kubernetes Connection
         run: kubectl cluster-info

       - name: List Pods
         run: kubectl get pods
