name: Deployment

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Please provide the release version'
        required: true
      rabbitmq:
        description: 'Please provide the image tag'
        required: true

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Configure kubectl
         run: |
           ls -ltra ~
           kubectl get pod
           echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
           kubectl config use-context ${{ secrets.KUBECONFIG }}
           kubectl config get-contexts
