name: Deployment

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Please provide the release version'
        required: true
        default: ''
      rabbitmq:
        description: 'Please provide the image tag'
        required: true
        default: ''

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions-hub/kubectl@master
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Apply Kubernetes Manifests with Inputs
        run: |
          kubectl version
          kubectl config get-contexts
          echo "manifest updated ${{ inputs.release }}"

      - name: Verify Deployment
        run: |
          echo "Deployment completed"
